version: '3.7'
services:
  telegram-bot:
    build: .
    restart: unless-stopped
    environment:
      - GATEWAY_ENDPOINT
      - TELEGRAM_TOKEN
networks:
  default:
    external:
      name: beuthbot_network